spring:
  cloud:
    nacos:
      server-addr: 192.168.2.211:8848
  application:
    name: mahumall-third-party
server:
  port: 30000
#配置到nacos配置中心
#alibaba:
#  cloud:
#    access-key: LTAI5tG1eLWeyzHa55q8N21U
#    secret-key: N7gOTMaLz9ex7vn0w2ug4RHYLe0JO9
#    oss:
#      endpoint: oss-cn-shenzhen.aliyuncs.com
#      bucket: mahumall
