spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.210:3306/mahumall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.2.211:8848
  application:
    name: mahumall-ware
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000
myRabbitmq:
  MQConfig:
    queues: stock.release.stock.queue
    delayQueue: stock.delay.queue
    eventExchange: stock-event-exchange
    routingKey: stock.locked
    letterRoutingKey: stock.release
    # 库存自动过期时间 单位:(毫秒)
    ttl: 40000
