spring:
  cloud:
    gateway:
      routes:
        #会员服务路由
        - id: member_route
          uri: lb://mahumall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        #商品服务的路由
        - id: product_route
          uri: lb://mahumall-product
          predicates:
            - Path=/api/product/**
          filters:
            # api去掉其他保留
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        #商品服务的路由
        - id: coupon_route
          uri: lb://mahumall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            # api去掉其他保留
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        #库存服务的路由
        - id: ware_route
          uri: lb://mahumall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            # api去掉其他保留
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        #第三方服务路由
        - id: third_part_route
          uri: lb://mahumall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        #剩下以api开头的请求都给renren-fast后端处理
        - id: admin_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://renren-fast
          #以api为开头的断言
          predicates:
            - Path=/api/**
          filters:
            # 重写路径，按照renren-fast的路径规则
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

        #nginx反代商城首页
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-product
          # host为 xx.xx.mahumall.com多级域名都可以访问
          predicates:
            - Host=www.mahumall.com,mahumall.com,item.mahumall.com

        #nginx反代商城搜索
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-search
          # host为 search.mahumall.com多级域名都可以访问
          predicates:
            - Host=search.mahumall.com
        #nginx反代商城认证
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-auth
          # host为 search.mahumall.com多级域名都可以访问
          predicates:
            - Host=auth.mahumall.com
        #nginx反代购物车认证
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-cart
          # host为 search.mahumall.com多级域名都可以访问
          predicates:
            - Host=cart.mahumall.com
        #nginx反代订单认证
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-order
          # host为 order.mahumall.com多级域名都可以访问
          predicates:
            - Host=order.mahumall.com
        #nginx反代订单认证
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-member
          # host为 order.mahumall.com多级域名都可以访问
          predicates:
            - Host=member.mahumall.com

        #nginx反代订单认证
        - id: host_route
          #lb负载均衡，注册中心内服务名（项目名）
          uri: lb://mahumall-seckill
          # host为 order.mahumall.com多级域名都可以访问
          predicates:
            - Host=seckill.mahumall.com
