spring:
  cloud:
    gateway:
      routes:
        - id: nicenan_route
          uri: https://www.nicenan.cn
          predicates:
            - Query=url,nicenan
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
